const Type={
    "LOGIN":"LOGIN",
    "TOKEN": "TOKEN",
     "USERDETAILS": "USERDETAILS",
     "JSONDATA":"JSONDATA",
     "PROCESSINGARRAY":"PROCESSINGARRAY",
     "SHOWMODAL":"SHOWMODAL",
     "MODALDATA":"MODALDATA",
     "EDITEDPROCESSINGARRAY":"EDITEDPROCESSINGARRAY",
     "SHOWMODALCOMP":"SHOWMODALCOMP",
     "AMOUNTDATA":"AMOUNTDATA"
}

export default Type