const Type = {
    "LOGIN": "LOGIN",
    "TOKEN": "TOKEN",
    "USERDETAILS": "USERDETAILS",
    "JSONDATA": "JSONDATA",
    "PROCESSINGARRAY": "PROCESSINGARRAY",
    "SHOWMODAL": "SHOWMODAL",
    "MODALDATA": "MODALDATA",
    "EDITEDPROCESSINGARRAY": "EDITEDPROCESSINGARRAY",
    "SHOWMODALCOMP": "SHOWMODALCOMP",
    "AMOUNTDATA": "AMOUNTDATA",
    "RESETPROCESSINGARRAY": "RESETPROCESSINGARRAY",
    "RESETEDITEDPROCESSINGARRAY": "RESETEDITEDPROCESSINGARRAY",
    "SHOWMOADALCOMPBOOL": "SHOWMOADALCOMPBOOL",
    "REMOVEITEMS": "REMOVEITEMS",
    "UPDATE_OBJECT_FIELD": "UPDATE_OBJECT_FIELD",
    "ACCOUNTNAME": "ACCOUNTNAME",
    "PAYLOAD": "PAYLOAD",
    "UPDATEPAYLOAD": "UPDATEPAYLOAD",
    "NOTIFICATIONMSG":"NOTIFICATIONMSG",
    "NOTIFICATIONTYPE":"NOTIFICATIONTYPE",
    "SHOWLOADER":"SHOWLOADER",
    "ROWDATA":"ROWDATA"


}

export default Type